# Generated by Django 4.0.6 on 2022-09-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApisUsers', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
