# Generated by Django 4.0.6 on 2022-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApisUsers', '0003_alter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
    ]
